"""
GitHub Bot Comment Service
Handles posting code review comments to GitHub via the bot
"""

import os
import requests
from typing import Dict, Any, Optional
import logging

logger = logging.getLogger(__name__)

BOT_URL = os.getenv("BOT_URL", "http://localhost:3000")


class GitHubCommentService:
    """Service for posting comments to GitHub via the bot"""
    
    def __init__(self, bot_url: str = BOT_URL):
        self.bot_url = bot_url.rstrip('/')
        self.comment_endpoint = f"{self.bot_url}/trigger-comment"
        self.health_endpoint = f"{self.bot_url}/health"
    
    def post_review_comment(
        self,
        owner: str,
        repo: str,
        pull_number: int,
        body: str,
        installation_id: int
    ) -> Dict[str, Any]:
        """
        Post a code review comment to GitHub PR via bot.
        
        Args:
            owner: Repository owner
            repo: Repository name
            pull_number: PR number
            body: Comment body (markdown supported)
            installation_id: GitHub App installation ID
            
        Returns:
            Response from bot with success status
        """
        payload = {
            "owner": owner,
            "repo": repo,
            "pull_number": pull_number,
            "body": body,
            "installation_id": installation_id
        }
        
        try:
            logger.info(f"Posting comment to {owner}/{repo}#{pull_number}")
            
            response = requests.post(
                self.comment_endpoint,
                json=payload,
                timeout=30
            )
            
            response.raise_for_status()
            result = response.json()
            
            logger.info(f"Comment posted successfully: {result}")
            return {
                "success": True,
                "message": result.get("message", "Comment posted"),
                "status_code": response.status_code
            }
            
        except requests.exceptions.RequestException as e:
            logger.error(f"Failed to post comment: {e}")
            return {
                "success": False,
                "error": str(e),
                "message": "Failed to post comment to GitHub"
            }
    
    def format_review_as_comment(self, review_result: Dict[str, Any]) -> str:
        """
        Format review result as a GitHub comment with markdown.
        
        Args:
            review_result: Review result from LangGraph workflow
            
        Returns:
            Formatted markdown string
        """
        formatted_output = review_result.get("formatted_review", {})
        unit_tests = review_result.get("unit_tests", {})
        
        comment_parts = []
        
        comment_parts.append("# 🤖 Open Rabbit Code Review\n")
        
        # Summary section
        if "summary" in formatted_output:
            comment_parts.append("## 📋 Summary\n")
            comment_parts.append(f"{formatted_output['summary']}\n")
        
        # Comments section
        if "comments" in formatted_output and formatted_output["comments"]:
            comment_parts.append("## 💬 Code Review Comments\n")
            
            for idx, comment in enumerate(formatted_output["comments"], 1):
                file_path = comment.get("path", "Unknown file")
                line = comment.get("line", "N/A")
                body = comment.get("body", "No comment")
                
                comment_parts.append(f"### {idx}. `{file_path}` (Line {line})\n")
                comment_parts.append(f"{body}\n")
        
        # Unit tests section
        if unit_tests and unit_tests.get("files_generated"):
            comment_parts.append("## 🧪 Unit Tests Generated\n")
            comment_parts.append(f"**Framework:** {unit_tests.get('framework', 'Unknown')}\n")
            comment_parts.append(f"**Tests Created:** {unit_tests.get('test_count', 0)}\n")
            comment_parts.append("**Files:**\n")
            for file in unit_tests.get("files_generated", []):
                comment_parts.append(f"- `{file}`\n")
        
        # Footer
        comment_parts.append("\n---")
        comment_parts.append("\n*Review generated by [Open Rabbit](https://github.com/open-rabbit)*")
        
        return "\n".join(comment_parts)
    
    def health_check(self) -> Dict[str, Any]:
        """
        Check if bot service is healthy.
        
        Returns:
            Health status from bot
        """
        try:
            response = requests.get(self.health_endpoint, timeout=5)
            response.raise_for_status()
            return {
                "healthy": True,
                "status": response.json()
            }
        except Exception as e:
            logger.warning(f"Bot health check failed: {e}")
            return {
                "healthy": False,
                "error": str(e)
            }


def post_review_to_github(
    owner: str,
    repo: str,
    pull_number: int,
    review_result: Dict[str, Any],
    installation_id: int
) -> Dict[str, Any]:
    """
    Convenience function to post review result to GitHub.
    
    Args:
        owner: Repository owner
        repo: Repository name
        pull_number: PR number
        review_result: Complete review result from workflow
        installation_id: GitHub App installation ID
        
    Returns:
        Result of posting comment
    """
    service = GitHubCommentService()
    
    comment_body = service.format_review_as_comment(review_result)
    
    return service.post_review_comment(
        owner=owner,
        repo=repo,
        pull_number=pull_number,
        body=comment_body,
        installation_id=installation_id
    )
