"""Initial migration

Revision ID: 7c73d43efaf9
Revises: 
Create Date: 2025-12-30 11:39:30.929840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c73d43efaf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_install',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('org', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_install_id'), 'new_install', ['id'], unique=False)
    op.create_index(op.f('ix_new_install_name'), 'new_install', ['name'], unique=False)
    op.create_index(op.f('ix_new_install_org'), 'new_install', ['org'], unique=False)
    op.create_table('pull_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org', sa.String(), nullable=True),
    sa.Column('repo', sa.String(), nullable=True),
    sa.Column('pr_no', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('cnt', sa.Integer(), nullable=True),
    sa.Column('changed_files', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_request_branch'), 'pull_request', ['branch'], unique=False)
    op.create_index(op.f('ix_pull_request_cnt'), 'pull_request', ['cnt'], unique=False)
    op.create_index(op.f('ix_pull_request_id'), 'pull_request', ['id'], unique=False)
    op.create_index(op.f('ix_pull_request_org'), 'pull_request', ['org'], unique=False)
    op.create_index(op.f('ix_pull_request_pr_no'), 'pull_request', ['pr_no'], unique=False)
    op.create_index(op.f('ix_pull_request_repo'), 'pull_request', ['repo'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('sub', sa.Boolean(), nullable=True),
    sa.Column('org', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_org'), 'users', ['org'], unique=False)
    op.create_index(op.f('ix_users_sub'), 'users', ['sub'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sub'), table_name='users')
    op.drop_index(op.f('ix_users_org'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pull_request_repo'), table_name='pull_request')
    op.drop_index(op.f('ix_pull_request_pr_no'), table_name='pull_request')
    op.drop_index(op.f('ix_pull_request_org'), table_name='pull_request')
    op.drop_index(op.f('ix_pull_request_id'), table_name='pull_request')
    op.drop_index(op.f('ix_pull_request_cnt'), table_name='pull_request')
    op.drop_index(op.f('ix_pull_request_branch'), table_name='pull_request')
    op.drop_table('pull_request')
    op.drop_index(op.f('ix_new_install_org'), table_name='new_install')
    op.drop_index(op.f('ix_new_install_name'), table_name='new_install')
    op.drop_index(op.f('ix_new_install_id'), table_name='new_install')
    op.drop_table('new_install')
    # ### end Alembic commands ###
