"""add_agent_checkpoints_table

Revision ID: c3f7ba949ceb
Revises: 7c73d43efaf9
Create Date: 2025-12-30 12:05:37.311177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f7ba949ceb'
down_revision: Union[str, Sequence[str], None] = '7c73d43efaf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('repo', sa.String(length=255), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('current_node', sa.String(length=64), nullable=True),
    sa.Column('completed_nodes', sa.Text(), nullable=True),
    sa.Column('state_data', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_checkpoints_owner'), 'agent_checkpoints', ['owner'], unique=False)
    op.create_index(op.f('ix_agent_checkpoints_pr_number'), 'agent_checkpoints', ['pr_number'], unique=False)
    op.create_index(op.f('ix_agent_checkpoints_repo'), 'agent_checkpoints', ['repo'], unique=False)
    op.create_index(op.f('ix_agent_checkpoints_thread_id'), 'agent_checkpoints', ['thread_id'], unique=True)
    op.create_index('ix_checkpoint_pr_lookup', 'agent_checkpoints', ['owner', 'repo', 'pr_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_checkpoint_pr_lookup', table_name='agent_checkpoints')
    op.drop_index(op.f('ix_agent_checkpoints_thread_id'), table_name='agent_checkpoints')
    op.drop_index(op.f('ix_agent_checkpoints_repo'), table_name='agent_checkpoints')
    op.drop_index(op.f('ix_agent_checkpoints_pr_number'), table_name='agent_checkpoints')
    op.drop_index(op.f('ix_agent_checkpoints_owner'), table_name='agent_checkpoints')
    op.drop_table('agent_checkpoints')
    # ### end Alembic commands ###
